const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this beautiful beachfront cottage with stunning ocean views, direct beach access, and a peaceful private deck. Perfect for weekend getaways.",
    image: {
      url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=60",
      filename: "beachfront_cottage",
    },
    price: 180,
    location: "Malibu, California",
    country: "United States",
    category: "Beachfront",
    coordinates: [34.0259, -118.7798],
  },
  {
    title: "Modern Mountain Cabin",
    description: "Experience the ultimate mountain retreat in this cozy A-frame cabin. Features a wood-burning stove, private hot tub, and access to hiking trails.",
    image: {
      url: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=60",
      filename: "mountain_cabin",
    },
    price: 250,
    location: "Aspen, Colorado",
    country: "United States",
    category: "Cabins",
    coordinates: [39.1911, -106.8175],
  },
  {
    title: "Luxury Penthouse Suite",
    description: "Soak in skyline views from this luxury penthouse in the heart of Manhattan. Steps away from Central Park, shopping, and gourmet restaurants.",
    image: {
      url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=60",
      filename: "penthouse_suite",
    },
    price: 490,
    location: "New York, New York",
    country: "United States",
    category: "Iconic Cities",
    coordinates: [40.7128, -74.0060],
  },
  {
    title: "Historic Castle Chamber",
    description: "Live like royalty in this authentically restored castle suite. Includes medieval stone walls, a canopy bed, and beautiful landscaped gardens.",
    image: {
      url: "https://images.unsplash.com/photo-1508849789987-4e5333c12b78?auto=format&fit=crop&w=800&q=60",
      filename: "castle_chamber",
    },
    price: 320,
    location: "Edinburgh",
    country: "United Kingdom",
    category: "Castles",
    coordinates: [55.9533, -3.1883],
  },
  {
    title: "Tropical Pool Villa",
    description: "Indulge in paradise with your own private infinity pool, tropical garden shower, and open-concept luxury living space in Bali.",
    image: {
      url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=60",
      filename: "pool_villa",
    },
    price: 220,
    location: "Ubud, Bali",
    country: "Indonesia",
    category: "Amazing Pools",
    coordinates: [-8.5069, 115.2625],
  },
  {
    title: "Glamping Dome Oasis",
    description: "Sleep under the stars in this climate-controlled geodesic dome. Nestled in the stunning rock formations of the Mojave Desert.",
    image: {
      url: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=60",
      filename: "glamping_dome",
    },
    price: 150,
    location: "Joshua Tree, California",
    country: "United States",
    category: "Camping",
    coordinates: [34.1347, -116.3131],
  },
  {
    title: "Rustic Farm Stayhouse",
    description: "Relax at this operating organic olive farm and vineyard in Tuscany. Enjoy freshly cooked farm-to-table meals and historic surroundings.",
    image: {
      url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=800&q=60",
      filename: "farm_stay",
    },
    price: 130,
    location: "Florence, Tuscany",
    country: "Italy",
    category: "Farms",
    coordinates: [43.7696, 11.2558],
  },
  {
    title: "Icelandic Glass Cabin",
    description: "Watch the Northern Lights right from your bed through the panoramic glass walls of this architectural marvel in rural Iceland.",
    image: {
      url: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=60",
      filename: "glass_cabin",
    },
    price: 380,
    location: "Akureyri",
    country: "Iceland",
    category: "Arctic",
    coordinates: [65.6835, -18.0878],
  },
  {
    title: "Chic Shibuya Micro-Apartment",
    description: "Experience the pulse of Tokyo from this compact, high-tech studio apartment situated right next to Shibuya Crossing.",
    image: {
      url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=60",
      filename: "tokyo_room",
    },
    price: 95,
    location: "Shibuya, Tokyo",
    country: "Japan",
    category: "Rooms",
    coordinates: [35.6580, 139.7016],
  },
  {
    title: "A-Frame Forest Hideaway",
    description: "Nestled deep in the pine trees of the Pacific Northwest, this cozy A-frame offers a screen-free getaway to reconnect with nature.",
    image: {
      url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=800&q=60",
      filename: "forest_hideaway",
    },
    price: 165,
    location: "Portland, Oregon",
    country: "United States",
    category: "Mountains",
    coordinates: [45.5152, -122.6784],
  },
  {
    title: "Sun-Drenched Beach Villa",
    description: "An elegant whitewashed cliffside villa overlooking the sparkling Aegean Sea. Classic Cycladic architecture with a modern luxury touch.",
    image: {
      url: "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=800&q=60",
      filename: "santorini_villa",
    },
    price: 420,
    location: "Oia, Santorini",
    country: "Greece",
    category: "Beachfront",
    coordinates: [36.4618, 25.3753],
  },
  {
    title: "Secluded Lake Chalet",
    description: "A gorgeous lakefront cabin with its own private pier, kayaks, and outdoor bonfire pit. The ultimate summer vacation spot.",
    image: {
      url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=800&q=60",
      filename: "lake_chalet",
    },
    price: 280,
    location: "Lake Tahoe, Nevada",
    country: "United States",
    category: "Cabins",
    coordinates: [39.0968, -120.0324],
  },
  {
    title: "Canal-View Heritage Townhouse",
    description: "A historic 17th-century merchant house along the Prinsengracht Canal. Beautiful exposed beam structure, steep stairs, and luxury fixtures.",
    image: {
      url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=60",
      filename: "amsterdam_townhouse",
    },
    price: 260,
    location: "Amsterdam",
    country: "Netherlands",
    category: "Iconic Cities",
    coordinates: [52.3676, 4.9041],
  },
  {
    title: "Fairytale French Chateau",
    description: "Immerse yourself in history in a wing of a historic French chateau. Stroll the manicured hedges and enjoy world-class wine tours.",
    image: {
      url: "https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?auto=format&fit=crop&w=800&q=60",
      filename: "chateau",
    },
    price: 650,
    location: "Loire Valley",
    country: "France",
    category: "Castles",
    coordinates: [47.4116, 0.9999],
  },
  {
    title: "Infinity Pool Cliffside Suite",
    description: "Perched high on the cliffs of the Amalfi Coast, this suite features standard luxury, private butler service, and a breathtaking infinity pool.",
    image: {
      url: "https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=60",
      filename: "amalfi_suite",
    },
    price: 850,
    location: "Positano",
    country: "Italy",
    category: "Amazing Pools",
    coordinates: [40.6281, 14.4850],
  },
  {
    title: "Luxury Safari Tent",
    description: "Enjoy wild game viewing from the deck of your luxury canvas suite. Includes en-suite bathroom, king bed, and guided safari tours.",
    image: {
      url: "https://images.unsplash.com/photo-1486916856992-e4db22c8df33?auto=format&fit=crop&w=800&q=60",
      filename: "safari_tent",
    },
    price: 340,
    location: "Serengeti National Park",
    country: "Tanzania",
    category: "Camping",
    coordinates: [-2.1540, 34.6857],
  },
  {
    title: "Vineyard Farmhouse Cottage",
    description: "Charming cottage nestled right next to rows of Cabernet vines. Enjoy complimentary wine tastings and a private garden deck.",
    image: {
      url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=60",
      filename: "vineyard_cottage",
    },
    price: 210,
    location: "Napa Valley, California",
    country: "United States",
    category: "Farms",
    coordinates: [38.5025, -122.2654],
  },
  {
    title: "Snow Glass Dome",
    description: "Stay warm in a thermal glass dome while surrounding yourself with snow-covered trees and a star-studded sky in Finnish Lapland.",
    image: {
      url: "https://images.unsplash.com/photo-1517760444937-f6397edcbbcd?auto=format&fit=crop&w=800&q=60",
      filename: "snow_dome",
    },
    price: 450,
    location: "Lapland",
    country: "Finland",
    category: "Arctic",
    coordinates: [67.9222, 26.5046],
  },
  {
    title: "Historic Townhouse Room",
    description: "A large, sunlit bedroom with an antique desk and vintage accents in a gorgeous Georgian townhouse close to central London sights.",
    image: {
      url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=60",
      filename: "london_room",
    },
    price: 80,
    location: "Kensington, London",
    country: "United Kingdom",
    category: "Rooms",
    coordinates: [51.5014, -0.1921],
  },
  {
    title: "Zermatt Luxury Chalet",
    description: "Ski-in, ski-out luxury chalet in Zermatt facing the majestic Matterhorn. Features a spa area, sauna, and outdoor terrace.",
    image: {
      url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=60",
      filename: "zermatt_chalet",
    },
    price: 720,
    location: "Zermatt",
    country: "Switzerland",
    category: "Mountains",
    coordinates: [46.0207, 7.7491],
  },
  {
    title: "Private Desert Oasis Villa",
    description: "An ultra-modern desert villa complete with dune buggy access, a private oasis pool, and stunning sunrises over rolling red sands.",
    image: {
      url: "https://images.unsplash.com/photo-1544984243-ec57ea16fe25?auto=format&fit=crop&w=800&q=60",
      filename: "desert_villa",
    },
    price: 600,
    location: "Dubai Desert",
    country: "United Arab Emirates",
    category: "Trending",
    coordinates: [25.2048, 55.2708],
  },
  {
    title: "Boho Beachfront Loft",
    description: "Live the slow life in this beautifully curated eco-loft right on the white sands of Tulum. Complete with swing chairs and sea breezes.",
    image: {
      url: "https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&w=800&q=60",
      filename: "tulum_loft",
    },
    price: 240,
    location: "Tulum, Quintana Roo",
    country: "Mexico",
    category: "Trending",
    coordinates: [20.2114, -87.4654],
  },
];

module.exports = { data: sampleListings };
